In [1]:
# Initial imports
import pandas as pd
from pathlib import Path

In [2]:
#https://www.wunderground.com/history/daily/us/ny/new-york-city/KLGA
# Due to the fact that we couldnt get historical weather data with an API or extract - 
# We had to take a manual approach and decided to collect the data by creating our own dataset

df = pd.read_csv(Path('data/weather_nyc.csv'), parse_dates=True, index_col='date')

#sort the data by date
df.sort_index(ascending=True, inplace=True)

df.head()

,temp_max,temp_avg,temp_min,dew_point_max,dew_point_avg,dew_point_min,humidity_max,humidity_avg,humidity_min,wind_max,wind_avg,wind_min
date,,,,,,,,,,,,
2010-01-01,39,35.5,33,34,13.0,0,96,86.3,73,21,5.0,0
2010-01-02,32,25.3,18,27,15.7,6,86,67.4,55,32,22.4,16
2010-01-03,23,20.7,18,14,9.8,5,74,62.8,57,32,25.5,21
2010-01-04,31,24.7,21,15,12.0,10,66,58.7,47,23,18.3,14
2010-01-05,31,26.4,22,15,13.4,11,65,58.4,52,22,16.8,12

In [3]:
# Remove irrelvant columns
df_final = df.drop(['temp_max', 'temp_min', 'dew_point_max', 'dew_point_min', 'humidity_max', 'humidity_min', 'wind_max', 'wind_min'], axis = 1)

In [4]:
# save filtered Weather data for NYC

df_final.to_csv('data/weather_nyc_final.csv', index=True)